/**
 * Chennai bulk-waste empanelment clarity gap — two vendors, four zones, July 25 expiry.
 *
 * Dev:  `npm run db:seed:chennai-bulk-waste-empanelment-july-2026`
 * Live: `npm run db:seed:chennai-bulk-waste-empanelment-july-2026:live`
 */
import { config as loadEnv } from "dotenv";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { and, eq } from "drizzle-orm";
import * as schema from "../src/db/schema";
import { articles, cities } from "../src/db/schema/tables";
import { revalidateNewsAfterSeed } from "./lib/revalidate-news-after-seed";

const HERO_IMAGE_URL =
  "/images/articles/chennai-bulk-waste-generators-swm-rules-2026-registration-deadline.jpg";

const GCC_SITE = "https://chennaicorporation.gov.in/";
const GCC_PORTAL = "https://gccservices.in/bulkwaste/register";
const RELATED_BWG_REGISTRATION =
  "/chennai-local-news/chennai-bulk-waste-generators-swm-rules-2026-registration-deadline";
const RELATED_NGT_COLLECTION =
  "/chennai-local-news/chennai-ngt-gcc-wet-dry-waste-separate-collection-days";
const RELATED_ZONES =
  "/chennai-local-news/chennai-corporation-zones-current-15-proposed-20-map-explained";

/** Empanelment expiry shown on GCC’s two-provider list (IST end of day). */
const EMPANELMENT_ENDS_AT = "2026-07-25T18:29:59.000Z";

const live =
  process.env.SEED_LIVE === "1" || process.argv.includes("--live");

if (live) {
  loadEnv({ path: ".env.production.local" });
} else {
  loadEnv({ path: "secrets/database.local.env" });
  loadEnv({ path: ".env.local" });
  loadEnv({ path: ".env" });
}

const url = process.env.DATABASE_URL;
if (!url) {
  console.error(
    live
      ? "Live: DATABASE_URL missing (.env.production.local)."
      : "DATABASE_URL missing — add to .env.local or secrets/database.local.env",
  );
  process.exit(1);
}

const db = drizzle(neon(url), { schema });

const SLUG = "chennai-bulk-waste-empanelment-two-vendors-four-zones-july-2026";

async function main() {
  const [city] = await db
    .select({ id: cities.id })
    .from(cities)
    .where(eq(cities.slug, "chennai"))
    .limit(1);

  if (!city) {
    console.error("City slug 'chennai' not found. Run db:seed or create city first.");
    process.exit(1);
  }

  const publishedAt = new Date("2026-07-20T05:00:00.000Z");
  const now = new Date();

  const reportBody = `## Key takeaways

- Greater Chennai Corporation has begun enforcing the **Solid Waste Management Rules, 2026**, but public records do not clearly explain who is authorised to collect and process bulk waste across all **15 zones**.
- The GCC website currently lists only **two** empanelled providers — covering **Zones 1, 2, 7 and 14** — both with the same expiry date of **25 July 2026**.
- An Additional Status Report filed before the NGT (Southern Zone) describes a different arrangement: an initial group of **14** authorised providers, later shifted to **zone concessionaires** and direct **GCC** collection in Zones **4, 7 and 8**.
- The national Rules require **four-stream** segregation, but the vendor document mentions only **wet and dry** waste.
- Enforcement and registration are advancing; a citywide, zone-wise operational pathway is still missing from the public domain.

## Summary

**Chennai, July 2026** — The Solid Waste Management Rules, 2026 have introduced a significantly more structured compliance framework for apartments, hotels, hospitals, educational institutions, restaurants, malls, information-technology parks, commercial establishments and other Bulk Waste Generators (BWGs).

The Rules were notified by the Union Ministry of Environment, Forest and Climate Change on **27 January 2026**, and came into force on **1 April 2026**, replacing the Solid Waste Management Rules, 2016. They require segregation of municipal solid waste into four streams: wet waste, dry waste, sanitary waste and special-care waste.

In Chennai, however, a basic operational question remains insufficiently answered in the public domain:

**Who exactly is authorised to collect, transport, process and recycle the different categories of waste generated by Bulk Waste Generators in each of the city’s 15 zones?**

The Greater Chennai Corporation has issued registration and compliance directions to Bulk Waste Generators. It has also initiated enforcement action. But the vendor and service-provider information available on the Corporation’s website remains limited and does not fully explain the system currently being implemented.

## GCC website shows only two empanelled providers

The Solid Waste Management Department of the Greater Chennai Corporation currently hosts a document titled:

**“Details of Service Providers Empanelled for Handling Wet Waste & Dry Waste for Bulk Waste Generators.”**

The document lists only two service providers:

| Service provider | Waste category | Zones allotted | Expiry date |
| --- | --- | ---: | ---: |
| Earth Recycler Private Limited | Wet and dry waste | Zones 7 and 14 | 25 July 2026 |
| Yokesh Enterprises | Wet and dry waste | Zones 1 and 2 | 25 July 2026 |

The official document therefore identifies providers for only **four of Chennai’s 15 zones**. Both entries carry the same expiry date of **25 July 2026**.

The document does not state:

- when the empanelment applications were invited;
- whether the selection was made through an Expression of Interest, tender or another procedure;
- how many applications were received;
- what eligibility and evaluation criteria were followed;
- which authority or committee approved the providers;
- whether any rate structure was approved;
- who serves the remaining **11** zones;
- whether fresh empanelment, renewal or extension is proposed after 25 July.

The absence of this information does not by itself establish that the selection was improper. It does, however, mean that the procedure cannot be independently understood from the public document currently displayed on the GCC website.

This distinction is important. The issue is not an allegation against the two companies. The issue is the lack of a complete and publicly accessible administrative framework explaining the empanelment and its relationship with Chennai’s broader waste-collection system.

## GCC’s NGT filing describes a different collection arrangement

The uncertainty becomes more significant when the website document is compared with an Additional Status Report filed by the Greater Chennai Corporation before the National Green Tribunal’s Southern Zone.

The report is dated **6 July 2026**. It was submitted as part of a compiled filing carrying the date **12 July 2026**, in Original Application Nos. **50 of 2024** and **144 of 2025**. It also encloses minutes of a government review meeting held on **3 July 2026**.

In that filing, GCC stated that it had **initially engaged 14 authorised service providers** to collect segregated waste from Bulk Waste Generators.

However, GCC further stated that, following representations from elected representatives and public feedback, it had decided that bulk waste should instead be collected through the existing concessionaires operating in the respective zones.

According to the report:

- concessionaires collect BWG waste in concessionaire-operated zones;
- GCC vehicles directly collect waste in GCC-operated areas comprising Zones **4, 7 and 8**, covering **12** divisions.

This raises an obvious public-information gap.

The GCC website shows two empanelled providers covering Zones **1, 2, 7 and 14**. The NGT filing refers to an initial group of **14** authorised providers and says the collection system was subsequently shifted to existing concessionaires and GCC vehicles.

The documents available publicly do not clearly explain:

- the identities of all 14 authorised providers;
- the period during which they operated;
- the order through which collection was transferred to concessionaires;
- whether any of the 14 authorisations remain valid;
- whether the two currently listed companies are collectors, processors, recyclers or integrated service providers;
- why Zone **7** appears in the two-vendor list when GCC’s filing also identifies Zone 7 as a GCC-operated area;
- how the two-provider list fits into the concessionaire-based system.

A consolidated clarification from GCC is necessary to reconcile these records.

## Four waste streams, but the vendor document mentions only two

The Solid Waste Management Rules, 2026 require four-stream segregation at source:

1. Wet waste
2. Dry waste
3. Sanitary waste
4. Special-care waste

The national Rules also establish a centralised online system for registration, data reporting and tracking of collection, sorting, processing, recycling and disposal.

GCC’s own NGT filing describes the responsibilities of Bulk Waste Generators in Chennai.

According to the Corporation, BWGs must:

- segregate waste at source;
- compost or biomethanise wet waste within their premises;
- channel recyclable dry waste through authorised recyclers;
- hand over sanitary waste, special-care waste and residual rejects to GCC for scientific disposal.

The current GCC vendor document, however, identifies the two providers only as handlers of “wet and dry waste.” It does not explain the service pathway for sanitary waste, special-care waste or residual rejects.

This creates practical uncertainty for a Bulk Waste Generator attempting to remain compliant.

For example, an apartment complex, hotel, hospital or educational institution may need to know:

- whether wet waste must be processed entirely on-site;
- whether off-site wet-waste collection is permitted;
- which recyclers are officially authorised for dry waste;
- who will collect sanitary waste;
- where special-care waste must be handed over;
- whether the zonal concessionaire is responsible for all residual waste;
- what records or certificates must be retained as proof of compliance;
- whether separate charges can be collected by concessionaires or service providers.

A citywide, zone-wise and waste-stream-wise operational guideline would provide clarity on these issues.

## Earlier GCC empanelment exercise disclosed more information

An older empanelment press release available on the GCC website provides a useful comparison.

That document states that GCC had invited Expressions of Interest from agencies providing biodegradable solid-waste processing and recycling services to Bulk Waste Generators and other establishments requiring such services.

It records that:

- **30** Expressions of Interest were received;
- the applications were scrutinised by GCC;
- **18** firms were shortlisted for biodegradable or wet-waste processing;
- the authorised firms were valid for **one year** from their respective dates of authorisation.

The older document therefore disclosed at least the number of applications received, the broad scrutiny process, the category of service and the names of multiple shortlisted providers.

The present two-provider document contains substantially less procedural information.

The exact date of the older press release is not visibly stated in the document text available online. It should therefore be referred to as an older or legacy GCC empanelment document unless the Corporation provides the dated original proceedings.

## Registration and enforcement are progressing

It would be inaccurate to state that GCC has taken no action under the Solid Waste Management Rules, 2026.

The Corporation’s July filing says that it has:

- launched an online registration portal;
- identified Bulk Waste Generators;
- issued letters seeking registration;
- conducted awareness activities;
- designated monitoring officers;
- started penal action against non-compliant establishments.

However, GCC’s own status report contains two different registration figures.

One paragraph states that, out of **3,184** identified BWGs, **1,652** had registered. Immediately afterwards, the “Present Status” section records **2,602** registered BWGs out of the same total of 3,184.

The minutes of the **3 July** meeting also record **2,602** registrations, representing more than **81 per cent** of identified BWGs.

The difference could be the result of information being updated at different stages while the report was compiled. Nevertheless, the document does not clearly date the two figures, and GCC should clarify the current verified registration total.

The 3 July meeting minutes further state that GCC had begun imposing a fine of **₹5,000** on BWGs found violating the prescribed requirements. Zonal officers were instructed to expedite registration and complete the process within **15 days**.

When enforcement is being intensified, the underlying service system must be equally clear.

A Bulk Waste Generator should not be left uncertain about which entity it is legally required or permitted to engage, particularly when failure to comply may result in penalties.

## GCC’s waste-management challenge remains substantial

According to GCC’s July status report, Chennai generates approximately **6,500 metric tonnes** of municipal solid waste every day.

The Corporation stated that around **750** tonnes per day were being processed through existing infrastructure such as micro-composting centres, Bio-CNG plants, material-recovery facilities, decentralised compost yards, plastic-baling centres and incineration facilities.

The remaining approximately **5,750** tonnes per day were being transported to the Kodungaiyur and Perungudi dump yards. These figures are GCC’s own estimates submitted before the NGT and should be understood as officially reported figures rather than independently audited data.

A transparent and effective Bulk Waste Generator system is therefore not merely an administrative requirement. Large waste generators can significantly reduce the volume of mixed waste entering the municipal collection and dumping system when segregation, processing and recycling are properly implemented.

But compliance depends on a clear chain of responsibility.

The waste generator must know who collects each waste stream. The collector must know where it can lawfully transport the material. The processor or recycler must hold the required authorisation. GCC must be able to verify the movement and final disposal of the waste.

Without a publicly understandable system, responsibility can become fragmented between generators, private vendors, concessionaires, recyclers, zonal officials and municipal vehicles.`.trim();

  const analysisBody = `## The July 25 expiry requires immediate clarification

The expiry date shown against both currently listed service providers is **25 July 2026**.

GCC should clarify before that date whether:

- the existing empanelments are being renewed;
- a fresh list is being prepared;
- the two firms will continue under an extension;
- the empanelled-provider model has been replaced entirely by concessionaire collection;
- BWGs may independently engage recyclers authorised by TNPCB or CPCB;
- a revised zone-wise list will be published;
- sanitary and special-care waste will be collected directly by GCC;
- a standard rate or user-fee mechanism will apply.

The answer cannot remain distributed across a one-page vendor list, an older empanelment press release, portal instructions, concessionaire arrangements and a status report filed before the NGT.

## What GCC should publish

The Greater Chennai Corporation should place a consolidated implementation document on its official website containing:

### 1. Zone-wise responsibility matrix

It should identify the agency responsible for BWG collection in every zone, including the relevant concessionaire, GCC division or empanelled provider.

### 2. Waste-stream-wise service pathway

The document should separately explain the permitted arrangements for wet, dry, sanitary, special-care and residual waste.

### 3. Complete authorised-provider list

The list should include the provider’s name, authorisation category, approving authority, validity period, allotted zones, processing facility and contact information.

### 4. Selection and empanelment records

GCC should publish the EOI or tender notice, eligibility criteria, evaluation process, committee approval and final proceedings.

### 5. Rate and user-fee framework

BWGs should know whether charges are regulated, negotiated privately or collected through an approved municipal framework.

### 6. Compliance documentation

GCC should specify the receipts, manifests, processing certificates, weighment records and annual returns that generators must maintain.

### 7. Grievance and appeal mechanism

A defined officer or portal should address service refusal, overcharging, failure to collect, unauthorised disposal and disputes over penalties.

## Transparency is necessary for compliance

The Solid Waste Management Rules, 2026 place greater responsibility on large waste generators. That shift is necessary for a city facing severe pressure on its collection, processing and disposal infrastructure.

But responsibility must be supported by clarity.

Greater Chennai Corporation has begun identifying, registering, monitoring and penalising Bulk Waste Generators. Its own records also show that the collection model has changed — from authorised service providers to concessionaires and direct GCC collection in certain areas.

What remains missing is a single, current and comprehensive public document explaining how the system works across Chennai.

The central question is therefore not whether waste generators must comply. They clearly must.

The question is whether GCC has provided them with a sufficiently transparent, consistent and citywide operational pathway to achieve that compliance.

With the two service-provider entries currently shown on the GCC website scheduled to expire on **25 July 2026**, that clarification has become urgent.

## Related reading on mychennaicity.in

- [Chennai bulk waste generators: 15 days to register under SWM Rules 2026](${RELATED_BWG_REGISTRATION})
- [NGT direction on wet and dry waste collection days](${RELATED_NGT_COLLECTION})
- [Chennai Corporation zones: 15 vs 20 explained](${RELATED_ZONES})
- [Register on the GCC bulk-waste portal](${GCC_PORTAL})

## Editorial note

This report is based on the Solid Waste Management Rules, 2026 notified by the Union Ministry of Environment, Forest and Climate Change; documents published by the Greater Chennai Corporation; and GCC’s July 2026 Additional Status Report filed before the National Green Tribunal, Southern Zone. The article does not allege wrongdoing by any listed service provider. It examines gaps and apparent inconsistencies in the public information available about Chennai’s bulk-waste collection and empanelment framework.`.trim();

  const body = `${reportBody}\n\n---\n\n${analysisBody}`;

  const [existing] = await db
    .select({ id: articles.id })
    .from(articles)
    .where(and(eq(articles.cityId, city.id), eq(articles.slug, SLUG)))
    .limit(1);

  const values = {
    cityId: city.id,
    slug: SLUG,
    title:
      "Who collects bulk waste in Chennai? GCC lists two firms for only 4 of 15 zones — both expire July 25",
    summary:
      "GCC’s empanelment page names only two bulk-waste vendors covering four of 15 zones, both ending 25 July 2026. Public records still do not explain citywide who is authorised to collect and process BWG waste.",
    dek: "Two firms. Four zones. A July 25 deadline. Chennai’s public records still do not say who covers bulk waste across the rest of the city.",
    body,
    reportBody,
    analysisBody,
    category: "Chennai",
    areaHubSlug: null as string | null,
    status: "published" as const,
    publishedAt,
    featured: true,
    heroImageUrl: HERO_IMAGE_URL,
    sourceUrl: GCC_SITE,
    sourceName:
      "Greater Chennai Corporation public documents; GCC Additional Status Report before NGT Southern Zone (July 2026); Solid Waste Management Rules, 2026",
    authorByline: "mychennaicity.in editorial",
    interactiveJson: {
      type: "faq",
      countdown: {
        title: "Listed empanelment expiry",
        subtitle:
          "Both providers currently shown on GCC’s wet- and dry-waste empanelment list carry a 25 July 2026 expiry. Confirm any renewal, extension or replacement list on the official GCC website.",
        endsAt: EMPANELMENT_ENDS_AT,
        ctaLabel: "GCC bulk-waste portal",
        ctaUrl: GCC_PORTAL,
        secondaryCtaLabel: "GCC website",
        secondaryCtaUrl: GCC_SITE,
        expiredLabel:
          "The listed empanelment date of 25 July 2026 has passed. Check GCC’s Solid Waste Management pages for any renewed, extended or replaced provider list before engaging a vendor.",
        note: "This countdown mirrors the date shown on GCC’s current two-provider document. It is not a registration deadline for Bulk Waste Generators.",
      },
      items: [
        {
          question: "How many empanelled bulk-waste providers does GCC currently list online?",
          answer:
            "As of this report, GCC’s Solid Waste Management Department document lists only two service providers — Earth Recycler Private Limited (Zones 7 and 14) and Yokesh Enterprises (Zones 1 and 2) — both for wet and dry waste, with expiry on 25 July 2026.",
        },
        {
          question: "What does GCC’s NGT filing say about bulk-waste collection?",
          answer:
            "In its July 2026 Additional Status Report before the NGT Southern Zone, GCC said it had initially engaged 14 authorised service providers, then decided — after representations and public feedback — that bulk waste should be collected through existing zonal concessionaires, with GCC vehicles collecting in GCC-operated areas in Zones 4, 7 and 8 (12 divisions).",
        },
        {
          question: "Why is Zone 7 mentioned in both records?",
          answer:
            "Zone 7 appears in the two-vendor website list (allotted to Earth Recycler Private Limited) and is also identified in the NGT filing as part of GCC-operated collection areas. Public documents do not yet reconcile how those roles fit together.",
        },
        {
          question: "Do the Solid Waste Management Rules, 2026 require four waste streams?",
          answer:
            "Yes. Generators must segregate wet, dry, sanitary and special-care waste. GCC’s current vendor document, however, identifies the two listed providers only for wet and dry waste and does not map pathways for sanitary waste, special-care waste or residual rejects.",
        },
        {
          question: "Does this article allege wrongdoing by the listed companies?",
          answer:
            "No. The report examines gaps and apparent inconsistencies in publicly available administrative information about empanelment and collection. It does not allege impropriety by Earth Recycler Private Limited, Yokesh Enterprises or any other provider.",
        },
        {
          question: "What should Bulk Waste Generators do while waiting for clearer guidance?",
          answer:
            "Complete required registration on official portals, follow four-stream segregation, process wet waste on-site where required, keep authorised collection and processing records, and verify any vendor against the latest GCC or pollution-control authorisations before contracting.",
        },
      ],
    } as Record<string, unknown>,
    updatedAt: now,
  };

  if (existing) {
    await db.update(articles).set(values).where(eq(articles.id, existing.id));
    console.log("[seed-bwg-empanelment] Refreshed article:", SLUG);
  } else {
    await db.insert(articles).values({
      ...values,
      createdAt: now,
    });
    console.log("[seed-bwg-empanelment] Inserted article:", SLUG);
  }

  console.log("[seed-bwg-empanelment] Public URL:", `/chennai-local-news/${SLUG}`);
  console.log("[seed-bwg-empanelment] Hero image:", HERO_IMAGE_URL);
  console.log("[seed-bwg-empanelment] Empanelment ends:", EMPANELMENT_ENDS_AT);

  if (live) {
    await revalidateNewsAfterSeed({
      slug: SLUG,
      label: "seed-bwg-empanelment",
    });
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
