/**
 * Ticket9 Chennai events — Jul–Sep 2026 (expanded city listing).
 * Sourced from https://www.theticket9.com/city/chennai
 * Enriched from Ticket9 event-page OG/JSON-LD metadata.
 * Seeded via scripts/seed-ticket9-chennai-events-2026.ts
 */

import type { ChennaiDiscoveryEvent } from "./chennai-discovery-events-2026";

export const TICKET9_CHENNAI_EVENTS_JUL_AUG_2026: ChennaiDiscoveryEvent[] = [
  {
    slug: "ticket9-madrasakka-live-tamil-sing-along-jamming-in-chennai",
    title: "MADRASAKKA - Live Tamil Sing-Along + Jamming in Chennai",
    category: "Concert",
    date: "2026-07-12",
    time: "17:00:00 to 19:30:00",
    venueName: "165° Hot Adyar",
    address: "Sardar Patel Road, Adyar, Chennai",
    locality: "Adyar",
    description: "Live Tamil sing-along and jamming night at 165° Hot, Adyar — karaoke-style community music evening.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/madrasakka-live-tamil-sing-along-jamming-in-chennai",
    notes: "Organiser: Unherd Music Community. Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-namma-chennai-juniorthon-4th-edition",
    title: "NAMMA CHENNAI JUNIORTHON 4TH EDITION",
    category: "Marathon",
    date: "2026-07-12",
    time: "08:00:00 to 10:30:00",
    venueName: "Nehru Park",
    address: "Nehru Park, Flowers Road, Sastri Nagar, Chetpet, Chennai, Tamil Nadu, India",
    locality: "Chetpet",
    description: "Kids juniorthon / run at Nehru Park, Chetpet — 4th edition.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/namma-chennai-juniorthon-4th-edition",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-state-level-inter-school-handwriting-competition-2026",
    title: "State level inter school handwriting competition 2026",
    category: "Competition",
    date: "2026-07-12",
    time: "10:00:00 to 12:30:00",
    venueName: "Decathlon Sports - Kilambakkam",
    address: "Decathlon Sports - Kilambakkam, GST Road, Kilambakkam, Vandalur, Chennai, Tamil Nadu, India",
    locality: "Kilambakkam",
    description: "Inter-school handwriting competition at Decathlon Sports, Kilambakkam.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/state-level-inter-school-handwriting-competition-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-the-unwritten-journey-a-stranger-photowalk",
    title: "The Unwritten Journey - A Stranger Photowalk",
    category: "Community",
    date: "2026-07-12",
    time: "06:00:00 to 08:30:00",
    venueName: "Edward Elliot's Beach",
    address: "Edward Elliot's Beach, Tamil Nadu",
    locality: "Elliot's Beach",
    description: "Free stranger photowalk community meetup at Edward Elliot's Beach.",
    ticketPrice: "Free",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/the-unwritten-journey-a-stranger-photowalk",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-chennai-puppy-yoga-journaling-circle-at-the-bistrograph",
    title: "Chennai Puppy Yoga + Journaling Circle at The Bistrograph",
    category: "Workshop",
    date: "2026-07-18",
    time: "11:00:00 to 13:30:00",
    venueName: "The Bistrograph",
    address: "The Bistrograph, Chennai",
    locality: "Chennai",
    description: "Puppy yoga and journaling circle at The Bistrograph, Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/chennai-puppy-yoga-journaling-circle-at-the-bistrograph",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-founder-circle-edition-12",
    title: "Founder Circle Edition 12",
    category: "Meetups",
    date: "2026-07-18",
    time: "09:00:00 to 11:30:00",
    venueName: "Velachery",
    address: "Velachery, Chennai, Tamil Nadu, India",
    locality: "Velachery",
    description: "Founder Circle networking meetup (Edition 12) in Velachery.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/founder-circle-edition-12",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-pets-day-out-2026",
    title: "PETS DAY OUT 2026",
    category: "Pets",
    date: "2026-07-18 to 2026-07-19",
    time: "10:00:00 to 20:00:00",
    venueName: "Wings Convention Centre",
    address: "St Georges, New Bupathy Nagar, Kilpauk, Chennai",
    locality: "Kilpauk",
    description: "Large pet festival for pet parents and animal lovers — fashion show, exotic animals, free anti-rabies vaccine drive, and brand stalls.",
    ticketPrice: "₹249 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/pets-day-out-2026",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-state-level-inter-school-athletic-championship-2026",
    title: "State level inter school athletic championship 2026",
    category: "Sports",
    date: "2026-07-18",
    time: "09:00:00 to 11:30:00",
    venueName: "SDAT Nehru Park",
    address: "SDAT Nehru Park, Poonamallee High Road, Sastri Nagar, Nehru Park, Chennai, Tamil Nadu, India",
    locality: "Chennai",
    description: "Inter-school athletic championship at SDAT Nehru Park, Chetpet.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/state-level-inter-school-athletic-championship-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-chennai-clay-keychains-with-puppies-at-sage-lavender",
    title: "Chennai Clay Keychains with Puppies at Sage & Lavender",
    category: "Workshop",
    date: "2026-07-19",
    time: "10:30:00 to 13:00:00",
    venueName: "Sage & Lavender",
    address: "Sage & Lavender, Chennai",
    locality: "Chennai",
    description: "Hands-on clay keychain workshop with puppies at Sage & Lavender, Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/chennai-clay-keychains-with-puppies-at-sage-lavender",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-galatta-digital-stars-2026-4th-edition",
    title: "Galatta Digital Stars 2026 - 4th Edition",
    category: "Live Shows",
    date: "2026-07-19",
    time: "10:00:00 to 13:00:00",
    venueName: "Kalaivanar Arangam",
    address: "Kalaivanar Arangam, Chennai",
    locality: "Triplicane",
    description: "Galatta Media's 4th edition celebrating digital icons, creators, and changemakers. Free entry, first-come first-served seating.",
    ticketPrice: "Free",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/galatta-digital-stars-2026-4th-edition",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-inter-school-chess-tournament-2026",
    title: "INTER SCHOOL CHESS TOURNAMENT 2026",
    category: "Competition",
    date: "2026-07-19",
    time: "09:00:00 to 11:30:00",
    venueName: "Dr.Mehta's International Smart School",
    address: "Dr.Mehta's International Smart School, Vanagaram-Ambattur Road, Athipet, Ambattur Industrial Estate, Chennai, Tamil Nadu, India",
    locality: "Ambattur",
    description: "Inter-school chess tournament at Dr. Mehta's International Smart School, Ambattur.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/inter-school-chess-tournament-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-state-level-drawing-carnivals-july-2026",
    title: "State Level Drawing Carnivals July 2026",
    category: "Arts",
    date: "2026-07-19",
    time: "09:00:00 to 11:30:00",
    venueName: "Dr.Mehta's International Smart School",
    address: "Dr.Mehta's International Smart School, Vanagaram-Ambattur Road, Athipet, Ambattur Industrial Estate, Chennai, Tamil Nadu, India",
    locality: "Ambattur",
    description: "State-level drawing carnival for kids at Dr. Mehta's International Smart School, Ambattur.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/state-level-drawing-carnivals-july-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-state-level-handwriting-competition-july-2026",
    title: "State Level Handwriting Competition July 2026",
    category: "Arts",
    date: "2026-07-19",
    time: "10:30:00 to 13:00:00",
    venueName: "Dr.Mehta's International Smart School",
    address: "Dr.Mehta's International Smart School, Vanagaram-Ambattur Road, Athipet, Ambattur Industrial Estate, Chennai, Tamil Nadu, India",
    locality: "Ambattur",
    description: "State-level handwriting competition for students at Dr. Mehta's International Smart School, Ambattur.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/state-level-handwriting-competition-july-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-state-level-kids-junior-badminton-tournament-2026",
    title: "State level kids & junior badminton tournament 2026",
    category: "Sports",
    date: "2026-07-19",
    time: "09:00:00 to 11:30:00",
    venueName: "Olympus Sports Villagio",
    address: "Olympus Sports Villagio, Koladi Road, Paruthippattu, Chennai, Tamil Nadu, India",
    locality: "Paruthippattu",
    description: "Kids and junior badminton tournament at Olympus Sports Villagio, Paruthippattu.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/state-level-kids-junior-badminton-tournament-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-state-level-kids-drawing-carnival-2026",
    title: "State level kids drawing carnival 2026",
    category: "Competition",
    date: "2026-07-19",
    time: "10:00:00 to 12:30:00",
    venueName: "Dr.Mehta's International Smart School",
    address: "Dr.Mehta's International Smart School, Vanagaram-Ambattur Road, Athipet, Ambattur Industrial Estate, Chennai, Tamil Nadu, India",
    locality: "Ambattur",
    description: "Kids drawing carnival at Dr. Mehta's International Smart School, Ambattur.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/state-level-kids-drawing-carnival-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-dia-diamonds-south-indian-nakshatram-awards-2026",
    title: "DIA Diamonds – South Indian Nakshatram Awards 2026",
    category: "Live Shows",
    date: "2026-07-22",
    time: "17:30:00 to 20:30:00",
    venueName: "Chennai Convention Centre",
    address: "Chennai Trade Centre Complex, Nandambakkam, Chennai",
    locality: "Nandambakkam",
    description: "South Indian Nakshatram Awards celebrating achievers across Tamil, Telugu, Kannada, and Malayalam industries.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/dia-diamonds-south-indian-nakshatram-awards-2026",
    notes: "Organiser: She India Magazine. Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-xy-cromax-go-paddie-she-miss-beauty-tamilnadu-2026",
    title: "XY Cromax Go Paddie – She Miss Beauty Tamilnadu 2026",
    category: "Live Shows",
    date: "2026-07-22",
    time: "10:30:00 to 13:30:00",
    venueName: "Chennai Convention Centre",
    address: "Chennai Trade Centre Complex, Nandambakkam, Chennai",
    locality: "Nandambakkam",
    description: "Grand finale of She Miss Beauty Tamil Nadu 2026 with runway showcases and celebrity guests.",
    ticketPrice: "₹899 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/xy-cromax-go-paddie-she-miss-beauty-tamilnadu-2026",
    notes: "Organiser: She India Magazine. Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-radicex",
    title: "RadicEx",
    category: "Workshop",
    date: "2026-07-23",
    time: "10:30:00 to 13:00:00",
    venueName: "TN-RISE Women Startup Council",
    address: "TN-RISE Women Startup Council, Guindy Industrial Estate, SIDCO Industrial Estate, Guindy",
    locality: "Guindy",
    description: "Startup / entrepreneurship workshop at TN-RISE Women Startup Council, Guindy.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/radicex",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-ctacis-thamizhar-4-0-1st-b2b-summit-for-tamil-entrepreneurs",
    title: "CTACIS Thamizhar 4.0 -1st B2B Summit for Tamil Entrepreneurs",
    category: "Meetups",
    date: "2026-07-24",
    time: "10:00:00 to 12:30:00",
    venueName: "Chennai",
    address: "Chennai, Tamil Nadu",
    locality: "Chennai",
    description: "B2B summit for Tamil entrepreneurs (CTACIS Thamizhar 4.0). Confirm venue and timing on Ticket9.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/ctacis-thamizhar-4-0-1st-b2b-summit-for-tamil-entrepreneurs",
    notes: "Ticket9 detail page was unavailable at import time; confirm details on the organiser listing. Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-64-gambit",
    title: "64 Gambit",
    category: "Sports",
    date: "2026-07-25",
    time: "08:00:00 to 11:00:00",
    venueName: "YMCA Royapettah",
    address: "West Cottage Road, Royapettah, Chennai",
    locality: "Royapettah",
    description: "Chess and strategy community event at YMCA Royapettah.",
    ticketPrice: "₹400 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/64-gambit",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-chennai-freelancers-club-monthly-meetup-july-2026",
    title: "Chennai Freelancers Club – Monthly Meetup July 2026",
    category: "Meetups",
    date: "2026-07-25",
    time: "10:00:00 to 13:00:00",
    venueName: "M2P Fintech",
    address: "Chennai",
    locality: "Chennai",
    description: "Monthly networking meetup for Chennai freelancers and independent professionals at M2P Fintech.",
    ticketPrice: "₹499 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/chennai-freelancers-club-monthly-meetup-july-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-the-iconic-dream-chakras-awards-2026",
    title: "The Iconic Dream Chakras Awards 2026",
    category: "Stage Show",
    date: "2026-07-25",
    time: "16:00:00 to 19:00:00",
    venueName: "Victoria Public Hall",
    address: "Near Central Railway Station, Park Town, Chennai",
    locality: "Park Town",
    description: "Awards night recognising achievers across industries at Victoria Public Hall.",
    ticketPrice: "₹300 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/the-iconic-dream-chakras-awards-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-love-vs-friendship-by-lea-i-sing-along-concert-chennai",
    title: "LOVE vs FRIENDSHIP by LEA I SING-ALONG CONCERT - CHENNAI",
    category: "Concert",
    date: "2026-07-26",
    time: "18:00:00 to 20:30:00",
    venueName: "The Music Academy, TT Krishnamachari Road",
    address: "The Music Academy, TT Krishnamachari Road, Chennai",
    locality: "Teynampet",
    description: "High-energy Tamil sing-along concert from LEA360Community — love melodies and friendship anthems from classic and modern cinema.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/love-vs-friendship-by-lea-i-sing-along-concert-chennai",
    featured: true,
    notes: "Organiser: LEA360COMMUNITY. Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-namma-besy-run-2026",
    title: "Namma Bessy Mile Run 2026",
    category: "Marathon",
    date: "2026-07-26",
    time: "05:00:00 to 08:00:00",
    venueName: "Olcott Memorial Higher Secondary School",
    address: "III Avenue Road, Besant Nagar, Chennai",
    locality: "Besant Nagar",
    description: "Community mile run in Besant Nagar for fitness and a social cause, with medals, T-shirts, and refreshments.",
    ticketPrice: "₹600 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/namma-besy-run-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-run-for-women-empowerment-2026",
    title: "Run for women empowerment 2026",
    category: "Marathon",
    date: "2026-07-26",
    time: "05:00:00 to 08:00:00",
    venueName: "C.S.I. Bain School",
    address: "Ormes Road, Kilpauk, Chennai",
    locality: "Kilpauk",
    description: "Community run supporting women empowerment — T-shirt, medal, certificate, breakfast, and prizes for top finishers.",
    ticketPrice: "₹349 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/run-for-women-empowerment-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-magic-money-tn-summit-2026-chennai",
    title: "Magic Money TN Summit 2026 – Chennai",
    category: "Meetups",
    date: "2026-08-01",
    time: "09:30:00 to 18:30:00",
    venueName: "Hilton Chennai",
    address: "Hilton Chennai, Guindy, Chennai",
    locality: "Guindy",
    description: "Premier financial learning summit by Magic 20 Tamil with fund managers, CEOs, and wealth experts — investing, mutual funds, and market outlook.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/magic-money-tn-summit-2026-chennai",
    featured: true,
    notes: "Organiser: Magic 20 Tamil. Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-thangame-thalapathy",
    title: "Thangame Thalapathy",
    category: "Concert",
    date: "2026-08-01",
    time: "18:00:00 to 20:00:00",
    venueName: "Medai - The Stage",
    address: "1st Cross Street, Chennai",
    locality: "Chennai",
    description: "Live concert celebrating Thalapathy Vijay hits at Medai – The Stage, Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/thangame-thalapathy",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-chennai-kidathon-2026",
    title: "CHENNAI KIDATHON 2026",
    category: "Marathon",
    date: "2026-08-02",
    time: "07:00:00 to 10:00:00",
    venueName: "SDAT Nehru Park",
    address: "Nehru Park, Chennai",
    locality: "Chennai",
    description: "Kids athletics / kidathon at Nehru Park (SDAT), Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/chennai-kidathon-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-bharat-option-traders-summit-chennai-2026",
    title: "BHARAT OPTION TRADERS SUMMIT CHENNAI - 2026",
    category: "Workshop",
    date: "2026-08-09",
    time: "08:30:00 to 17:30:00",
    venueName: "Anna Centenary Auditorium",
    address: "Gandhi Mandapam Road, Surya Nagar, Kotturpuram, Chennai",
    locality: "Kotturpuram",
    description: "South India's large option traders summit with workshops, speakers, and networking for traders and investors at Anna Centenary Auditorium.",
    ticketPrice: "₹499 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/bharat-option-traders-summit-chennai-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-independence-day-kidzathon-2026",
    title: "INDEPENDENCE DAY KIDZATHON 2026",
    category: "Sports",
    date: "2026-08-09",
    time: "06:00:00 to 09:00:00",
    venueName: "SDAT Nehru Park",
    address: "Chetpet, Chennai",
    locality: "Chetpet",
    description: "Kids running event around Independence Day at SDAT Nehru Park, Chetpet.",
    ticketPrice: "₹599 onwards",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/independence-day-kidzathon-2026",
    notes: "Organiser: Kalam Event Management on 9th Aug 2026 at SDAT Nehru Park, Chetpet, Chennai. Categories | Distance |Timing LKG | 75Mtrs. | 7:30am UKG | 75Mtrs. | 7:30am 1st STD | 100Mtrs. | 7:00am 2nd STD | 100Mtrs. | 7:00am 3rd STD | 200Mtrs. | 6:30am 4th STD | 300Mtrs. | 6:30am 5th & 6th STD | 500Mtrs. | 6:15am 7th & 8th STD | 800Mtrs. | 6:15am Open Category | 2KM | 8:30am Open Walkathon | 2KM | 8:30am BIB Collection on Event Date Prizes and Awards: Top 5 winners in each category will get a Trophy and all participants benefits included. All Participants will receive a Finisher Medal, Finisher Trophy, Participation Certificate, T-Shirt, BIB and a Refreshments Drink. Report 30Min before the event for Registration and don't forget to Carry your School ID and proof of Booking for the event. Thanks to our supporting partners: Venue: SDAT Nehru Park | Chetpet | Chennai. Show More Become a Sponsor Event Comforts & Features. Listed via Ticket9 (theticket9.com).",
  },
  // OMR Marathon curated as `omr-marathon-anti-drug-awareness-padur-august-2026`
  // (seed-event-omr-marathon-august-2026.ts) — omit Ticket9 stub to avoid duplicates.
  {
    slug: "ticket9-good-timing-ji-chennai",
    title: "Good Timing Ji - Chennai",
    category: "Comedy",
    date: "2026-08-15",
    time: "16:11:00 to 18:41:00",
    venueName: "M. S. Subbulakshmi Auditorium",
    address: "M. S. Subbulakshmi Auditorium, Tharamani, Chennai",
    locality: "Taramani",
    description: "Good Timing Ji comedy show at M. S. Subbulakshmi Auditorium, Taramani.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/good-timing-ji-chennai",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-pomblel-chennai",
    title: "Pomblel (Chennai)",
    category: "Comedy",
    date: "2026-08-15",
    time: "19:00:00 to 21:30:00",
    venueName: "The Music Academy",
    address: "The Music Academy, TT Krishnamachari Road, Chennai",
    locality: "Chennai",
    description: "Pomblel comedy show at The Music Academy, Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/pomblel-chennai",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-the-green-chase-26",
    title: "THE GREEN CHASE '26",
    category: "Marathon",
    date: "2026-08-15",
    time: "04:30:00 to 07:00:00",
    venueName: "Chennai",
    address: "Chennai, Tamil Nadu, India",
    locality: "Chennai",
    description: "Independence Day season green marathon / chase run across Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/the-green-chase-26",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-frangipani-tour-chennai",
    title: "Frangipani Tour - Chennai",
    category: "Concert",
    date: "2026-08-22",
    time: "17:00:00 to 19:30:00",
    venueName: "The Music Academy",
    address: "The Music Academy, Gopalapuram, Chennai",
    locality: "Gopalapuram",
    description: "Frangipani Tour live music night at The Music Academy, Chennai.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/frangipani-tour-chennai",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-thiruporur-marathon",
    title: "Thiruporur marathon",
    category: "Marathon",
    date: "2026-08-30",
    time: "05:00:00 to 07:30:00",
    venueName: "Rakki Cinemas",
    address: "Rakki Cinemas, Kalavakkam, Thiruporur, Tamil Nadu, India",
    locality: "Porur",
    description: "Community marathon starting near Rakki Cinemas, Kalavakkam / Thiruporur.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/thiruporur-marathon",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-chennaiyil-chinna-kuyil",
    title: "Chennaiyil Chinna Kuyil",
    category: "Concert",
    date: "2026-09-05",
    time: "18:00:00 to 20:30:00",
    venueName: "Vels Kalaiarangam",
    address: "Vels Kalaiarangam, Sara Nagar Main Road, Rajiv Gandhi Nagar, Old Pallavaram, Chennai, Tamil Nadu, India",
    locality: "Pallavaram",
    description: "Tamil concert evening at Vels Kalaiarangam, Old Pallavaram.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/chennaiyil-chinna-kuyil",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-kalam-s-world-records-honour-ceremony-2026",
    title: "Kalam's World Records Honour Ceremony 2026",
    category: "Business",
    date: "2026-09-05",
    time: "14:00:00 to 16:30:00",
    venueName: "Sivananda Memorial Auditorium (SMA)",
    address: "Sivananda Memorial Auditorium (SMA), next to Primary Care Health Center in, Maraimalai Nagar, Tamil Nadu, India",
    locality: "Chennai",
    description: "Honour ceremony celebrating world-record achievers at Sivananda Memorial Auditorium.",
    ticketPrice: "Free",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/kalam-s-world-records-honour-ceremony-2026",
    notes: "Listed via Ticket9 (theticket9.com).",
  },
  {
    slug: "ticket9-my-dream-stage-2026",
    title: "My Dream Stage 2026",
    category: "Live Shows",
    date: "2026-09-05",
    time: "13:00:00 to 15:30:00",
    venueName: "Sivananda Memorial Auditorium (SMA)",
    address: "Sivananda Memorial Auditorium (SMA), next to Primary Care Health Center in, Maraimalai Nagar, Tamil Nadu, India",
    locality: "Chennai",
    description: "Live performance showcase at Sivananda Memorial Auditorium.",
    ticketPrice: "See Ticket9 for pricing",
    targetAudience: "Chennai residents and visitors",
    bookingLink: "https://www.theticket9.com/event/my-dream-stage-2026",
    featured: true,
    notes: "Listed via Ticket9 (theticket9.com).",
  },
];
